#!/usr/bin/env bash
# One-shot Platewire deploy/upgrade on the VPS supervisor (root).
#   ssh SuperAgent 'bash /opt/platewire/desk/scripts/server-deploy.sh'
#
# What it does:
#   1. generates every secret on first run (reuses them on re-run)
#   2. writes /opt/platewire/.env.docker  (bot token intentionally blank)
#   3. writes /opt/platewire/desk/.env.office (office runtime env)
#   4. backs the old database up to /root, then drops the volume (--wipe)
#   5. rebuilds and starts db + backend (loopback 127.0.0.1:8000)
#   6. seeds the ADMIN user
#
# Flags:
#   --wipe        drop the postgres volume before starting (destroys all history)
#   --no-build    start without rebuilding the image
set -euo pipefail

REPO=/opt/platewire
DESK="$REPO/desk"
COMPOSE=(docker compose -f "$REPO/docker-compose.yml" -f "$REPO/docker-compose.backend.yml" --env-file "$REPO/.env.docker")
ACCESS=/root/PLATEWIRE-ACCESS.txt
DEPLOY_LOG=/root/platewire-deploy.log

WIPE=0
BUILD=1
for arg in "$@"; do
  case "$arg" in
    --wipe) WIPE=1 ;;
    --no-build) BUILD=0 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

cd "$REPO"
command -v docker >/dev/null
command -v openssl >/dev/null

hex() { openssl rand -hex "${1:-16}"; }

gen() {  # gen <var-file> <KEY> <bytes>
  local file="$1" key="$2" bytes="$3" current
  current=$(grep -E "^${key}=" "$file" 2>/dev/null | head -1 | cut -d= -f2- || true)
  if [[ -n "$current" ]]; then printf '%s' "$current"; return; fi
  hex "$bytes"
}

touch "$REPO/.env.docker"
PG_PASS=$(gen "$REPO/.env.docker" POSTGRES_PASSWORD 16)
[[ -n "$PG_PASS" ]] || PG_PASS=$(hex 16)
ADMIN_PASS=$(gen "$REPO/.env.docker" ADMIN_PASSWORD 12)
[[ -n "$ADMIN_PASS" ]] || ADMIN_PASS=$(hex 12)
MCP_TOKEN=$(gen "$REPO/.env.docker" MCP_SERVICE_TOKEN 24)
[[ -n "$MCP_TOKEN" ]] || MCP_TOKEN=$(hex 24)
HOOK_SECRET=$(gen "$REPO/.env.docker" HERMES_WEBHOOK_SECRET 32)
[[ -n "$HOOK_SECRET" ]] || HOOK_SECRET=$(hex 32)

umask 077
cat > "$REPO/.env.docker" <<ENV
# Loopback collector stack — generated by desk/scripts/server-deploy.sh.
# No public HTTP, no Telegram polling here: the bot belongs to the Hermes gateway.
PUBLIC_APP_URL=http://127.0.0.1
HTTP_PORT=8080
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=platewire

PIPELINE_ENABLED=true

WINLINE_MLB_URL=https://winline.ru/stavki/sport/bejsbol/ssha/mlb
WINLINE_BASEBALL_URL=https://winline.ru/stavki/sport/bejsbol
FETCH_CONCURRENCY=3
ODDS_FETCH_RETRIES=3
ODDS_RETRY_DELAY_SECONDS=1.5

JWT_SECRET=$(hex 24)
JWT_EXPIRES_IN=12h
JWT_REMEMBER_EXPIRES_IN=30d
ADMIN_LOGIN=admin
ADMIN_PASSWORD=$ADMIN_PASS

# Hermes does the F5 math; keep backend AI off.
AI_ENABLED=false
AI_BASE_URL=
AI_API_KEY=
AI_TIMEOUT_SECONDS=120
AI_MAX_TOOL_ROUNDS=6
AI_DECISION_MODEL=
AI_DECISION_TEMPERATURE=0.1
AI_CURATION_MODEL=
AI_CURATION_TEMPERATURE=0.3
AI_CURATION_CRON_ENABLED=false

# Path secret: /mcp/\$MCP_SERVICE_TOKEN
MCP_SERVICE_TOKEN=$MCP_TOKEN

# Office dispatcher: collector -> desk/scripts/office_webhook.py -> Hermes agent.
# host.docker.internal is provided by docker-compose.backend.yml (host-gateway).
HERMES_WEBHOOK_URL=http://host.docker.internal:8645/webhooks/platewire
HERMES_WEBHOOK_SECRET=$HOOK_SECRET

# Telegram stays with the Hermes gateway (platewire-gateway.service), never here.
TELEGRAM_BOT_TOKEN=
TELEGRAM_BOT_USERNAME=
TELEGRAM_NOTIFY_ENABLED=false
TELEGRAM_NOTIFY_CHAT_IDS=
ENV

cat > "$DESK/.env.office" <<ENV
# Office runtime env — generated by server-deploy.sh.
PLATEWIRE_BASE_URL=http://127.0.0.1:8000/api/v1
PLATEWIRE_LOGIN=admin
PLATEWIRE_PASSWORD=$ADMIN_PASS
HERMES_HOME=/home/platewire/.hermes
PLATEWIRE_RUNTIME=$DESK/runtime
PLATEWIRE_WEBHOOK_SECRET=$HOOK_SECRET
# The collector posts from inside a container: accept the docker bridge, never
# the public interface (the firewall rule below is scoped to the bridge subnet).
PLATEWIRE_WEBHOOK_HOST=0.0.0.0
PLATEWIRE_PYTHON=/usr/bin/python3
PLATEWIRE_AGENT_TIMEOUT=900
PLATEWIRE_WORKER_TIMEOUT=600
PLATEWIRE_SKIP_TELEGRAM=0
ENV
chmod 600 "$DESK/.env.office"

# ufw must pass the collector's loopback-to-bridge traffic on the listener port.
if command -v ufw >/dev/null && ufw status 2>/dev/null | grep -q "^Status: active"; then
  ufw allow from 172.16.0.0/12 to any port 8645 proto tcp comment 'platewire office webhook (docker bridge)' >/dev/null 2>&1 || true
  echo "== ufw: allowed 8645 from the docker bridge subnets only"
fi

cat > "$ACCESS" <<TXT
Platewire on $(hostname) — written $(date -Iseconds)
Repo:    $REPO  ($(git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo '?'))
API:     http://127.0.0.1:8000/api/v1  (loopback only)
MCP:     http://127.0.0.1:8000/mcp/$MCP_TOKEN
Login:   admin / $ADMIN_PASS
Office:  $DESK  (env $DESK/.env.office)
Webhook: listening 127.0.0.1:8645/webhooks/platewire, secret in .env.docker + .env.office
Hermes:  HERMES_HOME=/home/platewire/.hermes (bot token there, untouched)
TXT
chmod 600 "$ACCESS"

echo "== secrets ready (PG $((${#PG_PASS})) chars, admin $((${#ADMIN_PASS})) chars, mcp $((${#MCP_TOKEN})), hook $((${#HOOK_SECRET})))"
echo "== details written to $ACCESS"

if [[ "$WIPE" == "1" ]]; then
  echo "== backing the old database up to /root/platewire-predrop.sql.gz"
  docker compose -f "$REPO/docker-compose.yml" --env-file "$REPO/.env.docker" exec -T db \
    pg_dump -U postgres -d platewire 2>/dev/null | gzip > /root/platewire-predrop.sql.gz || echo "   (backup skipped — db not running)"
  ls -lh /root/platewire-predrop.sql.gz || true
  echo "== dropping the stack and the postgres volume"
  "${COMPOSE[@]}" down -v --remove-orphans
fi

if [[ "$BUILD" == "1" ]]; then
  echo "== building the backend image"
  "${COMPOSE[@]}" build backend
fi

echo "== starting db + backend"
"${COMPOSE[@]}" up -d --remove-orphans db backend

echo "== waiting for the API on 127.0.0.1:8000"
for i in $(seq 1 60); do
  code=$(curl -s -o /dev/null -w '%{http_code}' -m 3 http://127.0.0.1:8000/api/v1/auth/login || true)
  if [[ "$code" != "000" && -n "$code" ]]; then echo "   api up after ${i}s (http $code)"; break; fi
  sleep 2
done

echo "== seeding the admin user"
"${COMPOSE[@]}" exec -T backend npx tsx prisma/seed.ts || echo "   (seed failed — run manually)"

echo "== containers"
"${COMPOSE[@]}" ps

echo "== done. Deploy log: $DEPLOY_LOG"
