/** Product copy — RU UI. */

export const copy = {
  brand: "Platewire",
  nav: {
    home: "Главная",
    archive: "Архив",
    settings: "Настройки",
    logout: "Выход",
    backToList: "К списку",
  },
  home: {
    eyebrow: "Сегодня",
    title: "Матчи",
    description: "Слайт и live. Откройте матч для линий, составов и погоды.",
    refresh: "Обновить",
    refreshing: "Обновляю…",
    empty: "На сегодня матчей пока нет.",
    live: "Live",
    loadFailed: "Не удалось загрузить матчи",
  },
  archive: {
    eyebrow: "Архив",
    title: "Прошедшие матчи",
    description: "Слайт по official date (NY).",
    empty: "На эту дату матчей нет.",
    loadFailed: "Не удалось загрузить архив",
  },
  match: {
    markets: "Линии F5",
    details: "Подробнее",
    tabs: {
      overview: "Обзор",
      lineups: "Составы",
      weather: "Погода",
    },
    coverageReady: "готово",
    coverageMissing: "нет данных",
    saveOdds: "Сохранить линии",
    unlockAuto: "Разблокировать авто",
  },
  settings: {
    eyebrow: "Настройки",
    title: "Настройки",
    description: "Пользователи и pipeline сбора данных.",
    usersTitle: "Пользователи",
    usersDescription: "Управление доступом (ADMIN)",
    usersLoadFailed: "Не удалось загрузить пользователей",
    loginPlaceholder: "логин",
    passwordPlaceholder: "пароль",
    createUser: "Создать пользователя",
    confirmCreateUserTitle: "Создать пользователя?",
    userCreated: "Пользователь создан",
    userCreateFailed: "Не удалось создать пользователя",
    blockUser: "Заблокировать",
    unblockUser: "Разблокировать",
    confirmToggleUserTitle: "Изменить статус?",
    userStatusUpdated: "Статус обновлён",
    userStatusFailed: "Не удалось изменить статус",
    pipelineTitle: "Pipeline / ops",
    pipelineLoadFailed: "Не удалось загрузить статус pipeline",
    runPipeline: "Запустить",
    confirmPipelineTitle: "Запустить pipeline?",
    pipelineStarted: "Pipeline запущен",
    pipelineFailed: "Не удалось запустить pipeline",
  },
  common: {
    loading: "Загрузка…",
    retry: "Повторить",
    openMatch: "Открыть матч",
    error: "Что-то пошло не так",
    apply: "Применить",
    reject: "Отклонить",
  },
} as const;

export type Copy = typeof copy;
