/** Product copy — RU UI with familiar EN betting terms. */

export const copy = {
  brand: "Platewire",
  nav: {
    home: "Главная",
    archive: "Архив",
    ledger: "Журнал",
    agent: "Агент",
    settings: "Настройки",
    logout: "Выход",
    backToList: "К списку",
  },
  home: {
    eyebrow: "Сегодня",
    title: "Матчи",
    description:
      "Live board + readiness. Откройте матч для odds, signals и составов.",
    refresh: "Обновить",
    refreshing: "Обновляю…",
    empty: "На сегодня матчей пока нет.",
    live: "Live",
    loadFailed: "Не удалось загрузить матчи",
  },
  archive: {
    eyebrow: "Архив",
    title: "Прошедшие матчи",
    description: "Слайт по official date (NY).",
    empty: "На эту дату матчей нет.",
    loadFailed: "Не удалось загрузить архив",
  },
  match: {
    markets: "Линии F5",
    slip: "Статус ставок",
    details: "Подробнее",
    tabs: {
      overview: "Обзор",
      ai: "AI",
      lineups: "Составы",
      weather: "Погода",
      timeline: "История",
    },
    coverageReady: "готово",
    coverageMissing: "нет данных",
    saveOdds: "Сохранить линии",
    unlockAuto: "Разблокировать авто",
  },
  ledger: {
    eyebrow: "Журнал",
    title: "Ставки F5",
    description: "Paper ledger по tracks prematch/inn1/inn2.",
    empty: "Пока нет записей.",
    pending: "Pending",
    win: "WIN",
    lose: "LOSE",
    push: "PUSH",
    counted: "Учёт",
    includeInStats: "Учитывать в статистике",
    excludeFromStats: "Исключить из статистики",
    exportExcel: "Excel",
    exportAll: "Excel все",
    loadFailed: "Не удалось загрузить журнал",
  },
  agent: {
    eyebrow: "Агент",
    title: "Чат с AI",
    description: "Research и proposals. Apply — только human ADMIN.",
    placeholder: "Например: почему падает ROI на тоталах?",
    send: "Отправить",
    sending: "Думаю…",
    proposals: "Предложения",
    formula: "Формула",
    review: "Review",
    emptyProposals: "Предложений пока нет.",
    toolsUsed: "Инструменты",
    loadFailed: "Не удалось загрузить агента",
    sendFailed: "Не удалось получить ответ",
    preview: "Проверить на ledger",
    previewTitle: "Применить предложение?",
    previewLoading: "Считаю бэктест…",
    previewFailed: "Не удалось построить preview",
    appliedAs: "Production переключён на",
    baselineStale: "Baseline устарел относительно текущей production — ниже live-бэктест.",
    validationBlocked: "Спека невалидна — применить нельзя",
    showResolved: "Итоговая спека",
    productionNow: "Production",
    proposalsHint:
      "Применить — диалог с live-бэктестом и итоговой спекой. Активную формулу смотри во вкладке «Формула».",
  },
  settings: {
    eyebrow: "Настройки",
    title: "Настройки",
    description: "Production-формула, версии, пользователи и pipeline.",
    formulaTitle: "Production FormulaSpec",
    validate: "Проверить",
    validOk: "Спека валидна",
    validFail: "Ошибки валидации",
    reset: "Сбросить",
    unsaved: "Есть несохранённые изменения",
    showAdvanced: "Показать advanced",
    hideAdvanced: "Скрыть advanced",
    confirmApplyTitle: "Применить как production?",
    versionLabel: "Метка версии",
    saved: "Сохранено как production",
    saveFailed: "Не удалось сохранить формулу",
    loadFailed: "Не удалось загрузить настройки",
    versions: "Версии",
    activate: "Активировать",
    confirmActivateTitle: "Активировать версию?",
    activated: "Production переключён",
    activateFailed: "Не удалось активировать версию",
    openVersion: "Открыть",
    loadVersion: "В редактор",
    versionDetailTitle: "Версия формулы",
    testOnLedger: "Тест на ledger",
    testRunning: "Replay…",
    testFailed: "Не удалось прогнать бэктест",
    testOk: "Бэктест готов",
    usersTitle: "Пользователи",
    usersDescription: "Управление доступом (ADMIN)",
    usersLoadFailed: "Не удалось загрузить пользователей",
    loginPlaceholder: "логин",
    passwordPlaceholder: "пароль",
    createUser: "Создать пользователя",
    confirmCreateUserTitle: "Создать пользователя?",
    userCreated: "Пользователь создан",
    userCreateFailed: "Не удалось создать пользователя",
    blockUser: "Заблокировать",
    unblockUser: "Разблокировать",
    confirmToggleUserTitle: "Изменить статус?",
    userStatusUpdated: "Статус обновлён",
    userStatusFailed: "Не удалось изменить статус",
    pipelineTitle: "Pipeline / ops",
    pipelineLoadFailed: "Не удалось загрузить статус pipeline",
    runPipeline: "Запустить",
    confirmPipelineTitle: "Запустить pipeline?",
    pipelineStarted: "Pipeline запущен",
    pipelineFailed: "Не удалось запустить pipeline",
  },
  common: {
    loading: "Загрузка…",
    retry: "Повторить",
    openMatch: "Открыть матч",
    error: "Что-то пошло не так",
    apply: "Применить",
    reject: "Отклонить",
  },
} as const;

export type Copy = typeof copy;
